apiVersion: deployments.plural.sh/v1alpha1
kind: ServiceDeployment
metadata:
  name: loki
  namespace: monitoring
spec:
  namespace: monitoring
  git:
    folder: helm-values
    ref: logstack
  configurationRef:
    name: basic-auth
    namespace: monitoring
  repositoryRef:
    kind: GitRepository
    name: monitoring
    namespace: monitoring
  contexts:
    - loki # binds the loki context from the tf stack to this service
  helm:
    version: 5.43.6
    chart: loki
    valuesFiles:
    - loki.yaml
    - loki.yaml.liquid
    repository:
      name: grafana
      namespace: monitoring
  clusterRef:
    kind: Cluster
    name: mgmt
    namespace: infra
