apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-grafana-datasource
  namespace: monitoring
  labels:
    grafana_datasource: 'loki'
data:
  datasource-loki.yaml: |-
    apiVersion: 1
    datasources:
    - name: Loki
      type: loki
      access: proxy
      orgId: 1
      uid: loki
      url: http://loki-gateway/loki/api:3100
      jsonData:
        manageAlerts: true
        alertmanagerUid: alertmanager
        derivedFields:
          - datasourceName: Tempo
            matcherRegex: "traceID=(\\w+)"
            name: TraceID
            url: "$${__value.raw}"
            datasourceUid: tempo
