apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-grafana-datasource
  namespace: monitoring
  labels:
    grafana_datasource: "1"
data:
  datasource-loki.yaml: |-
    apiVersion: 1
    datasources:
    - name: Loki
      type: loki
      access: proxy
      orgId: 1
      uid: loki
      url: http://loki-gateway.monitoring
      basicAuth: true
      basicAuthUser: user
      secureJsonData:
        basicAuthPassword: $LOKI_DATASOURCE_PASSWORD
        httpHeaderValue1: '1'
      jsonData:
        httpHeaderName1: 'X-Scope-OrgID'
