apiVersion: deployments.plural.sh/v1alpha1
kind: ServiceDeployment
metadata:
  name: prometheus-agent
  namespace: monitoring
spec:
  namespace: monitoring
  git:
    folder: helm-values
    ref: logstack
  repositoryRef:
    kind: GitRepository
    name: monitoring
    namespace: monitoring
  helm:
    version: 25.17.0
    chart: prometheus
    valuesFiles:
    - prometheus-agent.yaml
    repository:
      name: prometheus-community
      namespace: monitoring
  clusterRef:
    kind: Cluster
    name: mgmt
    namespace: infra
---
# make global so it's also deployed on the other clusters
apiVersion: deployments.plural.sh/v1alpha1
kind: GlobalService
metadata:
  name: prometheus-agent
  namespace: monitoring
spec:
  tags:
    stage: dev
  serviceRef:
    name: prometheus-agent
    namespace: monitoring

