apiVersion: v1
kind: Secret
metadata:
  name: basic-auth-loki
stringData:
  # .htpasswd key used by loki
  .htpasswd: {{ configuration.basicAuthHtpasswd }}
  #user: {{ configuration.basicAuthUser }}
  #password: {{ configuration.basicAuthPassword }}
  # auth key used by prometheus ingress basic auth
  auth: {{ configuration.basicAuthHtpasswd }}

