apiVersion: deployments.plural.sh/v1alpha1
kind: ServiceDeployment
metadata:
  name: promtail
  namespace: monitoring
spec:
  namespace: monitoring
  git:
    folder: helm-values
    ref: logstack
  repositoryRef:
    kind: GitRepository
    name: monitoring
    namespace: monitoring
  configurationRef:
    name: basic-auth
    namespace: monitoring
  helm:
    version: 6.15.5
    chart: promtail
    valuesFiles:
    - promtail.yaml
    - promtail.yaml.liquid
    repository:
      name: grafana
      namespace: monitoring
  clusterRef:
    kind: Cluster
    name: mgmt
    namespace: infra
---
# make global so it's also deployed on the other clusters
apiVersion: deployments.plural.sh/v1alpha1
kind: GlobalService
metadata:
  name: promtail
  namespace: monitoring
spec:
  tags:
    stage: dev
  serviceRef:
    name: promtail
    namespace: monitoring
