apiVersion: deployments.plural.sh/v1alpha1
kind: ServiceDeployment
metadata:
  name: opencost
  namespace: monitoring
spec:
  namespace: monitoring
  git:
    folder: helm-values
    ref: logstack
  repositoryRef:
    kind: GitRepository
    name: monitoring
    namespace: monitoring
  #contexts:
  #  - opencost # binds the loki context from the tf stack to this service
  helm:
    version: 1.31.0
    chart: opencost
    valuesFiles:
    - opencost.yaml
    - opencost.yaml.liquid
    repository:
      name: opencost
      namespace: monitoring
  clusterRef:
    kind: Cluster
    name: mgmt
    namespace: infra
