fullnameOverride: monitoring 

defaultRules:
  create: true
  rules:
    alertmanager: true
    etcd: true
    configReloaders: true
    general: true
    k8sContainerCpuUsageSecondsTotal: true
    k8sContainerMemoryCache: true
    k8sContainerMemoryRss: true
    k8sContainerMemorySwap: true
    k8sContainerResource: true
    k8sContainerMemoryWorkingSetBytes: true
    k8sPodOwner: true
    kubeApiserverAvailability: true
    kubeApiserverBurnrate: true
    kubeApiserverHistogram: true
    kubeApiserverSlos: true
    kubeControllerManager: true
    kubelet: true
    kubeProxy: true
    kubePrometheusGeneral: true
    kubePrometheusNodeRecording: true
    kubernetesApps: true
    kubernetesResources: true
    kubernetesStorage: true
    kubernetesSystem: true
    kubeSchedulerAlerting: true
    kubeSchedulerRecording: true
    kubeStateMetrics: true
    network: true
    node: true
    nodeExporterAlerting: true
    nodeExporterRecording: true
    prometheus: true
    prometheusOperator: true
    windows: true


alertmanager:
  enabled: true
  fullnameOverride: kps-alertmanager


prometheusOperator:
  tls:
    enabled: false
  admissionWebhooks:
    enabled: false
  prometheusConfigReloader:
    resources:
      requests:
        cpu: 200m
        memory: 50Mi
      limits:
        memory: 100Mi
additionalScrapeConfigs:
  - job_name: opencost
    honor_labels: true
    scrape_interval: 1m
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    dns_sd_configs:
    - names:
      - opencost.monitoring
      type: 'A'
      port: 9003
grafana:
  enabled: true
  fullnameOverride: kps-grafana
  envValueFrom:
    LOKI_DATASOURCE_PASSWORD:
      secretKeyRef:
        name: basic-auth
        key: password
  admin:
    password: admin # placeholder will get overwritten
    user: admin
  datasources.yaml:
    apiVersion: 1
    deleteDatasources:
    - name: Loki
      orgId: 1
  service:
    type: ClusterIP
  ingress:
    enabled: true
    path: /.*
    annotations:
      kubernetes.io/tls-acme: "true"
      kubernetes.io/ingress.class: "nginx"
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
      nginx.ingress.kubernetes.io/use-regex: "true"
    hosts:
    - grafana.boot-aws.onplural.sh
    tls:
    - hosts:
      - grafana.boot-aws.onplural.sh
      secretName: grafana-tls
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      labelValue: "1"
      provider:
        name: sidecar
        allowUiUpdates: true
        foldersFromFilesStructure: true
      searchNamespace: ALL
      folderAnnotation: k8s-sidecar-target-directory
      annotations: 
        k8s-sidecar-target-directory: "/tmp/dashboards/kubernetes"
    datasources:
      enabled: true
      searchNamespace: ALL
    plugins:
      enabled: false
      searchNamespace: ALL
prometheus:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      kubernetes.io/tls-acme: "true"
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
      nginx.ingress.kubernetes.io/auth-type: basic
      nginx.ingress.kubernetes.io/auth-secret: basic-auth
      nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
    hosts:
      - prometheus.boot-aws.onplural.sh
    tls:
      - secretName: prometheus-tls
        hosts:
          - prometheus.boot-aws.onplural.sh
    servicePort: 9090
    pathType: Prefix
    paths:
      - /.*
  prometheusSpec:
    enableFeatures:
      enableFeatures: -remote-write-receiver
    enableRemoteWriteReceiver: true
    remoteWriteDashboards:
      enabled: true

# monitored k8s components
kubeApiServer:
  enabled: true

kubelet:
  enabled: true

coreDns:
  enabled: true

# already monitored with coreDns
kubeDns:
  enabled: false

kubeProxy:
  enabled: true

kubeStateMetrics:
  enabled: true

kube-state-metrics:
  fullnameOverride: kps-kube-state-metrics
  selfMonitor:
    enabled: true

nodeExporter:
  enabled: true

prometheus-node-exporter:
  fullnameOverride: kps-node-exporter
  prometheus:
    monitor:
      enabled: true
  resources:
    requests:
      memory: 512Mi
      cpu: 250m
    limits:
      memory: 2048Mi

# EKS hides metrics for controller manager, scheduler, and etcd
# https://github.com/aws/eks-anywhere/issues/4405
# disable kube controller manager scraping
kubeControllerManager:
  enabled: false

# disable kube scheduler scraping
kubeScheduler:
  enabled: false

kubeEtcd:
  enabled: false


