server:
  retention: "1d"
  retentionSize: "1GB"
  global:
    ## How frequently to scrape targets by default
    ##
    scrape_interval: 1m
    ## How long until a scrape request times out
    ##
    scrape_timeout: 10s
    ## How frequently to evaluate rules
    ##
    evaluation_interval: 1m

alertmanager:
  enabled: true

prometheus-pushgateway:
  enabled: false

# monitored k8s components
kubeApiServer:
  enabled: true

kubelet:
  enabled: true

coreDns:
  enabled: true

# already monitored with coreDns
kubeDns:
  enabled: false

kubeProxy:
  enabled: true

kubeStateMetrics:
  enabled: true

kube-state-metrics:
  fullnameOverride: pa-kube-state-metrics
  selfMonitor:
    enabled: true

nodeExporter:
  enabled: true

prometheus-node-exporter:
  fullnameOverride: pa-node-exporter
  prometheus:
    monitor:
      enabled: true
  resources:
    requests:
      memory: 512Mi
      cpu: 250m
    limits:
      memory: 2048Mi

# EKS hides metrics for controller manager, scheduler, and etcd
# https://github.com/aws/eks-anywhere/issues/4405
# disable kube controller manager scraping
kubeControllerManager:
  enabled: false

kubeScheduler:
  enabled: false

kubeEtcd:
  enabled: false