apiVersion: v1
kind: Secret
metadata:
  name: basic-auth
stringData:
  .htpasswd: {{ configuration.basicAuthHtpasswd }}
  user: {{ configuration.basicAuthUser }}
  password: {{ configuration.basicAuthPassword }}
